# Generated by Django 5.0.6 on 2024-07-11 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_compra_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
