# Generated by Django 5.0.6 on 2024-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_detallecompra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compra_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
